framework:
   messenger:
      failure_transport: failed

      transports:
         # https://symfony.com/doc/current/messenger.html#transport-configuration
         async:
            dsn: '%env(RABBITMQ_DSN)%'
            options:
               exchange:
                  name: ticket_exchange
                  type: direct
                  default_publish_routing_key: ticket_routing_key
               queues:
                  ticket_auto_dispatch_queue:
                     binding_keys: [ticket_routing_key]
               auto_setup: false
            retry_strategy:
               max_retries: 3
               delay: 1000
               multiplier: 2
               max_delay: 0

         failed: 'doctrine://default?queue_name=failed'
         # sync: 'sync://'

      default_bus: messenger.bus.default

      buses:
         messenger.bus.default:
            middleware:
               - doctrine_ping_connection
               - doctrine_close_connection
               - doctrine_transaction
               - validation

      routing:
         Symfony\Component\Mailer\Messenger\SendEmailMessage: async
         Symfony\Component\Notifier\Message\ChatMessage: async
         Symfony\Component\Notifier\Message\SmsMessage: async
         App\Message\TicketAssignmentMessage: async

         # Route your messages to the transports
         'App\Message\MailAlert': async
