version: '3'

services:
   mailer:
      image: schickling/mailcatcher
      ports: [1025, 1080]

   rabbitmq:
      image: rabbitmq:3.7-management
      ports:
         - '5672:5672'
         - '15672:15672'
