version: '3'

services:
   mailer:
      image: schickling/mailcatcher
      ports: [1025, 1080]

   rabbitmq:
      image: rabbitmq:3.7-management
      ports:
         - '5672:5672'
         - '15672:15672'

   ###> symfony/mercure-bundle ###
   mercure:
      image: dunglas/mercure
      restart: unless-stopped
      environment:
         # Uncomment the following line to disable HTTPS,
         SERVER_NAME: ':80'
         MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_JWT_SECRET}
         MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_JWT_SECRET}
         # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
         MERCURE_EXTRA_DIRECTIVES: |
            cors_origins http://localhost http://localhost:3000 *
            anonymous false
            publisher_jwt_key ${MERCURE_JWT_SECRET}
            subscriber_jwt_key ${MERCURE_JWT_SECRET}
            allow_anonymous_subscribers false

      ports:
         - '3000:80'
      # Comment the following line to disable the development mode
      command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
      healthcheck:
         test: ['CMD', 'curl', '-f', 'https://localhost/healthz']
         timeout: 5s
         retries: 5
         start_period: 60s
      volumes:
         - mercure_data:/data
         - mercure_config:/config
###< symfony/mercure-bundle ###

volumes:
   ###> symfony/mercure-bundle ###
   mercure_data:
   mercure_config:
###< symfony/mercure-bundle ###
